"""Synthetic fixture corpora, generated deterministically from a fixed seed.

Three corpora, used by the test suite (acceptance gates 1-3):

* `valid_manifest()` -- realistic, fully-compliant tools that must produce
  ZERO findings against every provider in `providers.DEFAULT_PROVIDER_SET`.
  This is the false-flag-rate control.

* `planted_manifest()` -- one (or more) tool per rule class, each crafted so
  the defect is unambiguous, paired with the rule_id it must trigger. This
  is the detection-rate corpus.

* `per_provider_manifest()` -- a schema that is legal for one provider and
  illegal for a stricter one, to prove a fix does not "land on half its
  class" by over- or under-flagging.

Nothing here is randomized data used for correctness assertions -- the
defect *shapes* are fixed and hand-specified (randomness would make a
"detection failed" result ambiguous: bad luck vs. a real regression). The
`Random(SEED)` instance is used only for cosmetic variation (padding
strings to a target length, picking among synonymous benign values) so the
corpus is still reproducibly "generated by this repo from a fixed seed" per
the spec, not hand-typed data masquerading as a generator.
"""
from __future__ import annotations

import random
from dataclasses import dataclass

SEED = 20260902


@dataclass(frozen=True)
class PlantedDefect:
    rule_id: str
    tool_name: str
    note: str


def _rng() -> random.Random:
    return random.Random(SEED)


def _padded_description(prefix: str, target_len: int, rng: random.Random) -> str:
    filler_words = ["parameter", "value", "field", "note", "detail", "context", "usage"]
    out = prefix
    while len(out) < target_len:
        out += " " + rng.choice(filler_words)
    return out[:target_len] if len(out) > target_len else out


# ---------------------------------------------------------------------------
# Valid (clean) corpus -- must yield 0 findings against openai/anthropic/google
# ---------------------------------------------------------------------------


def valid_manifest() -> dict:
    rng = _rng()
    tools = [
        {
            "name": "get_weather",
            "description": _padded_description(
                "Look up the current weather for a named city.", 120, rng
            ),
            "inputSchema": {
                "type": "object",
                "properties": {
                    "city": {"type": "string", "minLength": 1, "maxLength": 100},
                    "units": {"type": "string", "enum": ["celsius", "fahrenheit"], "default": "celsius"},
                },
                "required": ["city"],
                "additionalProperties": False,
            },
        },
        {
            "name": "read_file",
            "description": _padded_description(
                "Read the contents of a file at the given path.", 90, rng
            ),
            "inputSchema": {
                "type": "object",
                "properties": {
                    "path": {"type": "string", "minLength": 1},
                    "encoding": {"type": "string", "enum": ["utf-8", "ascii"], "default": "utf-8"},
                },
                "required": ["path"],
                "additionalProperties": False,
            },
        },
        {
            "name": "calculate_sum",
            "description": _padded_description("Add a list of numbers together.", 80, rng),
            "inputSchema": {
                "type": "object",
                "properties": {
                    "numbers": {
                        "type": "array",
                        "items": {"type": "number"},
                        "minItems": 1,
                    },
                    "precision": {"type": "integer", "minimum": 0, "maximum": 10, "default": 2},
                },
                "required": ["numbers"],
                "additionalProperties": False,
            },
        },
        {
            "name": "search_web",
            "description": _padded_description("Search the web for a query string.", 100, rng),
            "inputSchema": {
                "type": "object",
                "properties": {
                    "query": {"type": "string", "minLength": 1, "maxLength": 500},
                    "filters": {
                        "type": "object",
                        "properties": {
                            "site": {"type": "string"},
                            "max_results": {"type": "integer", "minimum": 1, "maximum": 50, "default": 10},
                        },
                        "additionalProperties": False,
                    },
                },
                "required": ["query"],
                "additionalProperties": False,
            },
        },
        {
            "name": "send_email",
            "description": _padded_description(
                "Send an email with a subject and body to a recipient.", 110, rng
            ),
            "inputSchema": {
                "type": "object",
                "properties": {
                    "to": {"type": "string", "pattern": r"^[^@\s]+@[^@\s]+\.[^@\s]+$"},
                    "subject": {"type": "string", "maxLength": 200},
                    "body": {"type": "string", "maxLength": 5000},
                },
                "required": ["to", "subject", "body"],
                "additionalProperties": False,
            },
        },
    ]
    return {"tools": tools}


# ---------------------------------------------------------------------------
# Planted-defect corpus -- one tool per rule, paired with expected rule_id
# ---------------------------------------------------------------------------


def planted_manifest() -> tuple[dict, list[PlantedDefect]]:
    rng = _rng()
    tools = []
    defects: list[PlantedDefect] = []

    # 1. unsupported-keyword: 'not' is unsupported by openai and google.
    tools.append(
        {
            "name": "kw_violator",
            "description": _padded_description("Uses a keyword some providers reject.", 60, rng),
            "inputSchema": {
                "type": "object",
                "properties": {"x": {"type": "string"}},
                "not": {"type": "null"},
                "additionalProperties": False,
            },
        }
    )
    defects.append(PlantedDefect("unsupported-keyword", "kw_violator", "root 'not' keyword"))

    # 2. nesting-too-deep: 6 levels of nested objects, exceeds openai's cap of 5.
    deep_schema = {"type": "string"}
    for level in range(6, 0, -1):
        deep_schema = {
            "type": "object",
            "properties": {f"level{level}": deep_schema},
            "additionalProperties": False,
        }
    tools.append(
        {
            "name": "deep_nester",
            "description": _padded_description("Nests objects far deeper than providers allow.", 60, rng),
            "inputSchema": deep_schema,
        }
    )
    defects.append(PlantedDefect("nesting-too-deep", "deep_nester", "6 levels of object nesting"))

    # 3a. name-pattern: invalid characters.
    tools.append(
        {
            "name": "bad name!",
            "description": _padded_description("Tool name has a space and punctuation.", 60, rng),
            "inputSchema": {
                "type": "object",
                "properties": {"x": {"type": "string"}},
                "additionalProperties": False,
            },
        }
    )
    defects.append(PlantedDefect("name-pattern", "bad name!", "space + punctuation in name"))

    # 3b. name-pattern: too long for openai/google (max 64).
    long_name = "a_very_long_tool_name_" + ("x" * 60)
    tools.append(
        {
            "name": long_name,
            "description": _padded_description("Tool name is far too long.", 60, rng),
            "inputSchema": {
                "type": "object",
                "properties": {"x": {"type": "string"}},
                "additionalProperties": False,
            },
        }
    )
    defects.append(PlantedDefect("name-pattern", long_name, "name length exceeds provider caps"))

    # 4. description-too-long: 2000 chars, exceeds openai/google's 1024 cap.
    tools.append(
        {
            "name": "verbose_tool",
            "description": _padded_description("Extremely verbose tool.", 2000, rng),
            "inputSchema": {
                "type": "object",
                "properties": {"x": {"type": "string"}},
                "additionalProperties": False,
            },
        }
    )
    defects.append(PlantedDefect("description-too-long", "verbose_tool", "2000-char description"))

    # 5. required-missing-property.
    tools.append(
        {
            "name": "unsatisfiable_required",
            "description": _padded_description("Requires a property that does not exist.", 60, rng),
            "inputSchema": {
                "type": "object",
                "properties": {"x": {"type": "string"}},
                "required": ["x", "y_does_not_exist"],
                "additionalProperties": False,
            },
        }
    )
    defects.append(
        PlantedDefect("required-missing-property", "unsatisfiable_required", "'y_does_not_exist' not in properties")
    )

    # 6. additional-properties-open: object schema with additionalProperties unset.
    tools.append(
        {
            "name": "open_object",
            "description": _padded_description("Object schema never closes extra args.", 60, rng),
            "inputSchema": {
                "type": "object",
                "properties": {"x": {"type": "string"}},
                # additionalProperties intentionally omitted
            },
        }
    )
    defects.append(PlantedDefect("additional-properties-open", "open_object", "additionalProperties unset"))

    # 7. duplicate-tool-name: planted as a pair, appended after the loop below.
    dup_tool = {
        "name": "duplicate_tool",
        "description": _padded_description("First copy of a duplicated tool.", 60, rng),
        "inputSchema": {
            "type": "object",
            "properties": {"x": {"type": "string"}},
            "additionalProperties": False,
        },
    }
    tools.append(dup_tool)
    tools.append(dict(dup_tool))  # exact duplicate name
    defects.append(PlantedDefect("duplicate-tool-name", "duplicate_tool", "same name appears twice"))

    # 8a. empty-enum-or-bad-default: empty enum.
    tools.append(
        {
            "name": "empty_enum_tool",
            "description": _padded_description("Has an enum with no allowed values.", 60, rng),
            "inputSchema": {
                "type": "object",
                "properties": {"mode": {"type": "string", "enum": []}},
                "additionalProperties": False,
            },
        }
    )
    defects.append(PlantedDefect("empty-enum-or-bad-default", "empty_enum_tool", "enum: []"))

    # 8b. empty-enum-or-bad-default: default violates local schema (5 < minimum 10).
    tools.append(
        {
            "name": "bad_default_tool",
            "description": _padded_description("Default value violates its own bounds.", 60, rng),
            "inputSchema": {
                "type": "object",
                "properties": {
                    "count": {"type": "integer", "minimum": 10, "default": 5},
                },
                "additionalProperties": False,
            },
        }
    )
    defects.append(PlantedDefect("empty-enum-or-bad-default", "bad_default_tool", "default 5 < minimum 10"))

    # 9a. missing-input-schema: inputSchema absent entirely.
    tools.append(
        {
            "name": "no_schema_tool",
            "description": _padded_description("Has no inputSchema at all.", 60, rng),
        }
    )
    defects.append(PlantedDefect("missing-input-schema", "no_schema_tool", "inputSchema absent"))

    # 9b. missing-input-schema: inputSchema.type is not 'object'.
    tools.append(
        {
            "name": "wrong_type_schema_tool",
            "description": _padded_description("inputSchema.type is 'string', not 'object'.", 60, rng),
            "inputSchema": {"type": "string"},
        }
    )
    defects.append(PlantedDefect("missing-input-schema", "wrong_type_schema_tool", "inputSchema.type == 'string'"))

    return {"tools": tools}, defects


# ---------------------------------------------------------------------------
# Per-provider control: legal for one provider, illegal for a stricter one.
# ---------------------------------------------------------------------------


def per_provider_manifest() -> tuple[dict, dict]:
    """A schema nested 5 levels deep.

    openai's max_nesting_depth is 5 (legal, exactly at the cap) and
    anthropic's is 8 (legal). google's is 4 (illegal -- exceeds by one
    level). Used to prove a stricter-provider finding does not leak into a
    more permissive provider's report.
    """
    rng = _rng()
    schema = {"type": "string"}
    for level in range(5, 0, -1):
        schema = {
            "type": "object",
            "properties": {f"level{level}": schema},
            "additionalProperties": False,
        }
    tool = {
        "name": "moderately_nested",
        "description": _padded_description("Nested exactly at the openai cap, over google's.", 60, rng),
        "inputSchema": schema,
    }
    manifest = {"tools": [tool]}
    expectation = {
        "tool_name": "moderately_nested",
        "rule_id": "nesting-too-deep",
        "legal_provider": "openai",
        "illegal_provider": "google",
    }
    return manifest, expectation
